### ISSUE TITLE
Не проходит проверку https

### ISSUE THREAD

**Issue by sstyle** [Surzhikov/Telegram-Site-Helper-2.0#10]
Пишет ошибку. Однако сайт (весь) работает через нормальный сертификат. ispmanager + nginx. На 443 порту. Все как положено.

$_SERVER['HTTPS'] и $_SERVER['HTTP_X_HTTPS'] - не выдают ничего

Убрал проверку в скрипте. Чат на сайте появился, но менеджер не может залогиниться в бот. не отвечает ничего на авторизацию

upd: в виртуальный хост прописал SetEnvIf X-Forwarded-Proto https HTTPS=on установка теперь проходит нормально, но все по прежнему не работает.

**Comment by sstyle** [comment]
Оказывается не верно поставил сертификат. Теперь все ок

**Comment by NikGleb** [comment]
А можете описать, что именно было "неправильно"? У меня сертификат от letsencrypt, сайт получил A+, а вот бот также не может пройти проверку и не отвечает на авторизацию (при отключенной проверке).

**Comment by NikGleb** [comment]
В моем случае дело было не в сертификате, а в "allow_url_fopen = Off", что не позволяло делать корректные запросы к серверу telegram. На время установки переключил на "On" и вернул опять к "Off" после.
