### ISSUE TITLE
Бот не отвечает на команды

### ISSUE THREAD

**Issue by frvrndvr** [Surzhikov/Telegram-Site-Helper-2.0#5]
Установка прошла успешно, но бот молчит и не отвечает на "/login 1234"

**Comment by frvrndvr** [comment]
в окне чата сообщение - нет менеджеров онлайн

**Comment by LexeY4eg** [comment]
Аналогичная проблема. Заметил что после установки пришел ответ:
Telegram answer for setting webhook: {"ok":true,"result":true,"description":"Webhook was set"}
Хотя в статье на хабре в ответе есть еще параметр url: "https://.....webhook....php" думаю в этом проблема. БД - sqllite.

**Comment by frvrndvr** [comment]
Заработало после добавления www в адресную строку

**Comment by LexeY4eg** [comment]
Вы могли бы уточнить куда добавляли www? Изменяли хост на котором размещается вебхук? Я устанавливаю бота на хосте https://bot.[domain].ru/bot/telegram-site-helper-install.php

**Comment by LexeY4eg** [comment]
Поидее, когда я пишу боту команды, телеграм должен присылать мне запросы в telegram-site-helper-get-webhook_ххх.php. Я добавил в нем логгирование - запросы не приходят. Т.е. получается что веб хук не установился корректно, к сожалению не наблюдаю в телеграм API метода для просмотра теккущего значения веб хука, только метод для его установки. :(

**Comment by LexeY4eg** [comment]
Проблема была с сертификатом. Телеграм не проверяет домен https://core.telegram.org/bots/self-signed
